### ISSUE TITLE
Problems with dataflow.PrefetchData after updating to 0.9 version

### ISSUE THREAD

**Issue by zhangyu2ustc** [tensorpack/tensorpack#1036]
After updating to 0.9 version, I keep receiving this error message:
Traceback (most recent call last):
  File "./HCP_task_fmri_cnn_tensorpack_changesize_bk4_wm.py", line 1093, in <module>
    validation_data=val_set,validation_steps=100, verbose=1,shuffle=True,
  File "/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/keras/engine/training.py", line 2212, in fit_generator
    generator_output = next(output_generator)
  File "/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/keras/utils/data_utils.py", line 779, in get
    six.reraise(value.__class__, value, value.__traceback__)
  File "/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/six.py", line 693, in reraise
    raise value
  File "/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/keras/utils/data_utils.py", line 644, in _data_generator_task
    generator_output = next(self._generator)
  File "./HCP_task_fmri_cnn_tensorpack_changesize_bk4_wm.py", line 696, in data_pipe_3dcnn_block
    ds1 = dataflow.PrefetchData(ds1, buffer_size, 1)
  File "/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/dataflow/parallel.py", line 188, in __init__
    self._size = len(ds)
TypeError: 'float' object cannot be interpreted as an integer

The script works totally fine with the previous version 0.8. But I want to use the multi-gpu features from the new version. Could you please help me fixing this error?

my data_pipe function is listed in the following:
    assert data_type in ['train', 'val', 'test']
    assert flag_cnn in ['3d', '2d']
    assert fmri_files is not None
    isTrain = data_type == 'train'

    print('\n\nGenerating dataflow for %s datasets \n' % data_type)

    buffer_size = int(min(len(fmri_files), buffer_size))
    nr_thread = int(min(len(fmri_files), nr_thread))

    ds0 = gen_fmri_file(fmri_files, confound_files, label_matrix, data_type=data_type, train_percent=train_percent)
    print('dataflowSize is ' + str(ds0.size()))
    print('Loading data using %d threads with %d buffer_size ... \n' % (nr_thread, buffer_size))

    if target_name is None:
        target_name = np.unique(label_matrix)
    ##Subject_Num, Trial_Num = np.array(label_matrix).shape

    ####running the model
    start_time = time.clock()
    if flag_cnn == '2d':
        ds1 = dataflow.MultiThreadMapData(
            ds0, nr_thread=nr_thread,
            map_func=lambda dp: map_load_fmri_image_block(dp, target_name,block_dura=block_dura),
            buffer_size=buffer_size,
            strict=True)
    elif flag_cnn == '3d':
        ds1 = dataflow.MultiThreadMapData(
            ds0, nr_thread=nr_thread,
            map_func=lambda dp: map_load_fmri_image_3d_block(dp, target_name,block_dura=block_dura),
            buffer_size=buffer_size,
            strict=True)

    ds1 = dataflow.PrefetchData(ds1, buffer_size, 1)  ##returning error here

    ds1 = split_samples(ds1)  ##a self defined function for splitting data samples
    print('prefetch dataflowSize is ' + str(ds1.size()))
    ds_data_shape= ds1.data_info()
    Trial_Num = ds_data_shape[0]
    Block_dura = ds_data_shape[-1]
    print('%d #Trials/Samples per subject with %d channels in tc' % (Trial_Num,Block_dura))

    if isTrain:
        ds1 = dataflow.LocallyShuffleData(ds1, buffer_size=Trial_Num * buffer_size)

    ds1 = dataflow.BatchData(ds1, batch_size=batch_size, remainder=True)
    print('Time Usage of loading data in seconds: {} \n'.format(time.clock() - start_time))

    #ds1 = dataflow.PrefetchDataZMQ(ds1, nr_proc=1)
    #ds1._reset_once()
    ds1.reset_state()
    return ds1

### 4. Your environment:
  + Python version: py3.6
  + TF version: `python -c 'import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)'`. 1.12.0
  + Tensorpack version: `python -c 'import tensorpack; print(tensorpack.__version__);'`. 0.9
      You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`
      and see if your issue is already solved.
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell. tired both jupyter and shell
  + Hardware information, e.g. number of GPUs used. 2

About efficiency issues, PLEASE first read http://tensorpack.readthedocs.io/en/latest/tutorial/performance-tuning.html

**Comment by ppwwyyxx** [comment]
I cannot see evidence that this is a tensorpack issue. From the error log:
```
TypeError: 'float' object cannot be interpreted as an integer
```
It appears that your dataflow returns a float as its length, not an integer. You may want to check that.

**Comment by zhangyu2ustc** [comment]
Thanks for your help. Problem solved.

I have another errors when trying compile the CNN model use the KerasModel class.
    model_test_GPU_new.compile(optimizer=tf.train.AdamOptimizer(), loss='categorical_crossentropy', metrics='categorical_accuracy')
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/contrib/keras.py", line 267, in compile
    metrics=metrics)
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/contrib/keras.py", line 212, in setup_keras_trainer
    lambda: optimizer)
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/train/tower.py", line 214, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/train/trainers.py", line 193, in _setup_graph
    grad_list = self._builder.call_for_each_tower(tower_fn)
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 225, in call_for_each_tower
    use_vs=[False] + [True] * (len(self.towers) - 1))
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 121, in build_on_towers
    return DataParallelBuilder.call_for_each_tower(*args, **kwargs)
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 116, in call_for_each_tower
    ret.append(func())
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/train/tower.py", line 266, in get_grad_fn
    return compute_grad_from_inputs(*inputs)
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/train/tower.py", line 245, in compute_grad_from_inputs
    cost = get_cost_fn(*inputs)
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/tfutils/tower.py", line 286, in __call__
    output = self._tower_fn(*args)
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/contrib/keras.py", line 165, in get_cost
    outputs = model_caller(input_tensors)
  File "/home/yu/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/contrib/keras.py", line 106, in __call__
    outputs = model.outputs
AttributeError: 'Tensor' object has no attribute 'outputs'


**Here is my code:**

        train_gen = data_pipe_3dcnn_block(fmri_data_train, confounds_train, label_train,
                                          target_name=target_name, flag_cnn=Flag_CNN_Model,block_dura=block_dura,
                                          batch_size=batch_size, data_type='train', nr_thread=nr_thread, buffer_size=buffer_size)

        #########################################
        def one_hot(label):
            return np.eye(len(target_name))[label]

        train_gen = dataflow.MapDataComponent(train_gen, one_hot, 1)

        model_test_GPU_new = KerasModel(model_test_GPU,
                                        inputs_desc=[InputDesc(tf.float32, (None,) + img_shape, 'images')],
                                        targets_desc=[InputDesc(tf.uint8, (None, len(target_name)), 'labels')],
                                        input=train_gen, trainer=SyncMultiGPUTrainerReplicated(num_GPU))

        model_test_GPU_new.compile(optimizer=tf.train.AdamOptimizer(), loss='categorical_crossentropy', metrics='categorical_accuracy')
        callbacks = [ModelSaver(), GPUUtilizationTracker() ]

        ######start training the model
        model_test_GPU_new.fit(steps_per_epoch=100, max_epoch=100, callbacks=callbacks)

**Comment by zhangyu2ustc** [comment]
Thanks for your quick reply.
I actually used a keras model, with the function listed below:

def build_cnn_model_test(input_shape, Nlabels, filters=16, convsize=3, convsize2=5, poolsize=2, hidden_size=256, conv_layers=4):
    input0 = Input(shape=input_shape)
    drop1 = input0
    ####quickly reducing image dimension first
    for li in range(1):
        conv1 = Conv2D(filters, (convsize, convsize), strides=2, padding='same',activation='relu',
                    kernel_initializer='he_normal',kernel_regularizer=regularizers.l2(l2_reg))(drop1)
        conv1 = BatchNormalization()(conv1)
        drop1 = Dropout(0.25)(conv1)
        filters *= 2
    for li in range(conv_layers-1):
        conv1 = Conv2D(filters, convsize, padding='same',activation='relu',
                    kernel_initializer='he_normal',kernel_regularizer=regularizers.l2(l2_reg))(drop1)
        conv1 = BatchNormalization()(conv1)
        conv1 = Conv2D(filters, convsize2, padding='same',activation='relu',
                    kernel_initializer='he_normal',kernel_regularizer=regularizers.l2(l2_reg))(conv1)
        conv1 = BatchNormalization()(conv1)
        conv1 = Conv2D(filters, (convsize, convsize), strides=2, padding='same',activation='relu',
                    kernel_initializer='he_normal',kernel_regularizer=regularizers.l2(l2_reg))(conv1)
        conv1 = BatchNormalization()(conv1)
        drop1 = Dropout(0.25)(conv1)
        if (li+1) % 2 == 0:
            filters *= 2

    drop2 = drop1
    avg1 = AveragePooling2D(pool_size=(5, 5))(drop2)
    flat = Flatten()(avg1)
    hidden = Dense(hidden_size, kernel_initializer='he_normal',kernel_regularizer=regularizers.l2(l2_reg), activation='relu')(flat)
    drop3 = Dropout(0.4)(hidden)

    out = Dense(Nlabels, activation='softmax')(drop3)

    model = Model(inputs=input0, outputs=out)
    model.summary()

    return model

model_test_GPU = build_cnn_model_test(img_shape, nb_class)

**Comment by ppwwyyxx** [comment]
See examples at https://github.com/tensorpack/tensorpack/blob/master/examples/keras/mnist-keras-v2.py

You're not calling KerasModel with correct argument types.

**Comment by ppwwyyxx** [comment]
Your issue can probably fixed by upgrading tensorpack to github's master.
If not, please provide details following the issue template.

Please also note what's written in the example: https://github.com/tensorpack/tensorpack/tree/master/examples/keras#note

**Comment by zhangyu2ustc** [comment]
upgrading does not fix the issue.

If you're asking about an unexpected problem you met, use this template.
__PLEASE DO NOT DELETE THIS TEMPLATE, FILL IT__:

### 1. What you did:
I was trying to use multi-gpu for model training

(1) **If you're using examples, what's the command you run:**
following example: https://github.com/tensorpack/tensorpack/blob/master/examples/keras/imagenet-resnet-keras.py

(2) **If you're using examples, have you made any changes to the examples? Paste them here:**
change the optimizer to Adam:
  model = KerasModel(build_model_resnet50,
                                    inputs_desc=[InputDesc(tf.float32, (None,) + img_shape, 'images')],
                                    targets_desc=[InputDesc(tf.float32, (None, len(target_name)), 'labels')],
                                    input=train_gen, trainer=SyncMultiGPUTrainerReplicated(num_GPU)
                                    )
 model.compile(optimizer=tf.train.AdamOptimizer(learning_rate), loss='categorical_crossentropy', metrics='categorical_accuracy')

(3) **If not using examples, tell us what you did here:**

Note that we may not be able to investigate it if there is no reproducible code.
It's always better to paste what you did instead of describing them.

### 2. What you observed:

(1) **Include the ENTIRE logs here:**
[0109 12:20:48 @collection.py:151] Size of these collections were changed in tower1: (tf.GraphKeys.UPDATE_OPS: 68->136)
/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/graph_builder/training.py:320: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  "Reason: {} ".format(name, reason))
[0109 12:20:52 @training.py:320] WRN [ReplicatedTrainer] Do not know how to sync variable 'tower1/conv2d_34/kernel:0' across GPUs. Reason: Cannot find conv2d_34/kernel:0 in the graph! 
Traceback (most recent call last):
  File "./HCP_task_fmri_cnn_tensorpack_changesize_bk4_wm_test.py", line 822, in <module>
    model_test_GPU_new.compile(optimizer=tf.train.AdamOptimizer(learning_rate), loss='categorical_crossentropy', metrics='categorical_accuracy')
  File "/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/contrib/keras.py", line 267, in compile
    metrics=metrics)
  File "/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/contrib/keras.py", line 212, in setup_keras_trainer
    lambda: optimizer)
  File "/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/utils/argtools.py", line 176, in wrapper
    return func(*args, **kwargs)
  File "/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/train/tower.py", line 214, in setup_graph
    train_callbacks = self._setup_graph(input, get_cost_fn, get_opt_fn)
  File "/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/train/trainers.py", line 194, in _setup_graph
    self.train_op, post_init_op = self._builder.build(grad_list, get_opt_fn)
  File "/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 303, in build
    post_init_op = SyncMultiGPUReplicatedBuilder.get_post_init_ops()
  File "/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 345, in get_post_init_ops
    log_failure(v.name, "Cannot find {} in the graph!".format(realname))
  File "/home/yuzhang/tensorflow-py3.6/lib/python3.6/site-packages/tensorpack/graph_builder/training.py", line 322, in log_failure
    "The aforementioned variable is trainable, so this is probably a fatal error."
AssertionError: The aforementioned variable is trainable, so this is probably a fatal error.

It's always better to paste what you observed instead of describing them.

A part of logs is sometimes enough, but it's always better to paste as much as possible.

You can run a command with `CMD 2>&1 | tee logs.txt` to save all stdout & stderr logs to one file.

(2) **Other observations, if any:**
For example, CPU/GPU utilization, output images, tensorboard curves, if relevant to your issue.
[0109 12:20:38 @training.py:49] [DataParallel] Training a model of 2 towers.
[0109 12:20:38 @interface.py:31] Automatically applying QueueInput on the DataFlow.
[0109 12:20:38 @interface.py:43] Automatically applying StagingInput on the DataFlow.
[0109 12:20:38 @input_source.py:220] Setting up the queue 'QueueInput/input_queue' for CPU prefetching ...
[0109 12:20:38 @training.py:109] Building graph for training tower 0 on device /gpu:0 ...
[0109 12:20:43 @training.py:109] Building graph for training tower 1 on device /gpu:1 ...

### 3. What you expected, if not obvious.

If you expect higher accuracy, only in one of the two conditions can we help with it:
(1) You're unable to match the accuracy documented in tensorpack examples.
(2) It appears to be a tensorpack bug.

Otherwise, how to get high accuracy is a machine learning question and is
not our responsibility to figure out.

### 4. Your environment:
  + Python version: python3.6
  + TF version: `python -c 'import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)'`. 1.12.0
  + Tensorpack version: `python -c 'import tensorpack; print(tensorpack.__version__);'`.
      You can install Tensorpack master by `pip install -U git+https://github.com/ppwwyyxx/tensorpack.git`
      and see if your issue is already solved. 0.9
  + If you're not using tensorpack under a normal command line shell (e.g.,
    using an IDE or jupyter notebook), please retry under a normal command line shell.  in shell
  + Hardware information, e.g. number of GPUs used. 2

About efficiency issues, PLEASE first read http://tensorpack.readthedocs.io/en/latest/tutorial/performance-tuning.html

**Comment by zhangyu2ustc** [comment]
Upgrading again. Still the same version.
pip install -U git+https://github.com/ppwwyyxx/tensorpack.git
...
Successfully installed tensorpack-0.9.0.1

Yes. I have tested the example with fake_data using the two gpu setting. It worked.
Here, I only need training on multi-gpus without hyperparamter tuning of learning rate.

**Comment by zhangyu2ustc** [comment]
Plus, how was the number of iterations determined? I have tried to change my training set but still result in the same iterations. In my case, it is simply too large, taking 60526112 hours to finish using single gpu. How can I modify this value?

[0109 14:00:14 @inference_runner.py:97] [InferenceRunner] Will eval 62500000000 iterations

**Comment by ppwwyyxx** [comment]
[fit](https://tensorpack.readthedocs.io/modules/contrib.html#tensorpack.contrib.keras.KerasModel.fit) takes the same keyword arguments as [Trainer.train_with_defaults](https://tensorpack.readthedocs.io/modules/train.html#tensorpack.train.Trainer.train_with_defaults), which includes the number of steps in training. It's by default `dataflow.size()`.
The number of steps in inference is determined by your inference dataflow which you can obtain by `dataflow.size()`.

**Comment by zhangyu2ustc** [comment]
Is it possible to change the default value for validation_steps if I want to keep the validation_data option? Because my dataflow.size() is just a large value and meaningless.

**Comment by ppwwyyxx** [comment]
No. You should make sure the size is reasonable and make sure your dataflow does go back to the beginning and start producing the beginning of your dataset after `size()` number of datapoints have been produced.
Otherwise the inference results will be meaningless.

**Comment by ppwwyyxx** [comment]
Closing due to lack of activity. If you have more questions you can open a new issue.
